variables:
- template: /eng/common-variables.yml@self
- name: officialBuild
  value: ${{ and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}

- ${{ if eq(variables.officialBuild, 'true') }}:
  - template: /eng/common/templates-official/variables/pool-providers.yml@self
- ${{ if ne(variables.officialBuild, 'true') }}:
  - template: /eng/common/templates/variables/pool-providers.yml
- name: Build.Repository.Clean
  value: true
- name: _BuildConfig
  value: Release
- name: CheckNuGetSizesScript
  value: >-
    $nupkgs_large=(Get-ChildItem artifacts/packages/$(_BuildConfig)/Shipping -recurse -include "*.nupkg" | Select-Object Name,Length | Where-Object { $_.Length -gt 250*1MB });
    if ($nupkgs_large.Length -gt 0) { Write-Error "NuGet size exceeds 250MiB: $($nupkgs_large | Format-Table | Out-String)"; exit 1 }

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*

extends:
  template: dispatch.yml
  parameters:
    ${{ if eq(variables.officialBuild, 'true') }}:
      templateName: azure-pipelines-official.yml
    ${{ if ne(variables.officialBuild, 'true') }}:
      templateName: azure-pipelines-pr.yml
