<Project>

  <PropertyGroup>
    <!-- we don't need symbol packages for emsdk -->
    <AutoGenerateSymbolPackages>false</AutoGenerateSymbolPackages>
    <ProducesDotNetReleaseShippingAssets>true</ProducesDotNetReleaseShippingAssets>
  </PropertyGroup>

  <!-- The host-independent marker is built by every host, but registered only once. -->
  <ItemGroup Condition="'$(TargetRid)' != 'win-x64'">
    <Artifact Remove="$(ArtifactsNonShippingPackagesDir)Microsoft.NET.Runtime.Emscripten.Internal.*.nupkg" />
  </ItemGroup>

</Project>
